import os, json, logging, requests
from odoo import models, fields, api, _
from odoo.exceptions import ValidationError

_logger = logging.getLogger(__name__)
AI_URL = os.environ.get('AI_SERVICE_URL', 'http://ai_service:8000')

class HealthVitalRecord(models.Model):
    _name = 'health.vital.record'
    _description = 'Patient Vital Record'
    _order = 'recorded_at desc'

    def action_manual_save_close(self):
        """Dummy method just to give users a 'Save & Close' button that closes the popup wizard"""
        return {'type': 'ir.actions.act_window_close'}

    patient_id = fields.Many2one('health.patient', 'Patient', required=True, ondelete='cascade', index=True)
    type = fields.Selection([
        ('blood_pressure', 'Blood Pressure'),
        ('heart_rate', 'Heart Rate'),
        ('glucose', 'Glucose'),
        ('temperature', 'Temperature'),
        ('oxygen', 'Oxygen (SpO2)'),
        ('respiratory_rate', 'Respiratory Rate')
    ], string='Vital Type')
    
    value = fields.Float('Value/Systolic')
    value2 = fields.Float('Diastolic (for BP)')
    unit = fields.Char('Unit', compute='_compute_unit', store=True)

    recorded_at = fields.Datetime('Recorded At', default=fields.Datetime.now, required=True, index=True)
    
    ai_score = fields.Float('AI Score', readonly=True, help="Anomaly score from 0.0 to 100.0 generated by the AI.")
    ai_severity = fields.Selection([
        ('normal', 'Normal'),
        ('warning', 'Warning'),
        ('critical', 'Critical')
    ], string='AI Severity', readonly=True)
    anomaly_detected = fields.Boolean('Anomaly Detected', readonly=True, help="True if ML or Rule thresholds were violated.")
    
    # NEW FIELDS DEMANDED BY THE VIEW
    bp_systolic = fields.Float('BP Systolic')
    bp_diastolic = fields.Float('BP Diastolic')
    heart_rate = fields.Float('Heart Rate')
    spo2 = fields.Float('SpO2')
    temperature = fields.Float('Temperature')
    glucose = fields.Float('Glucose')
    respiratory_rate = fields.Float('Respiratory Rate')
    clinical_hints = fields.Text('Clinical Hints')
    parsed_clinical_hints = fields.Html('AI Clinical Analysis', compute='_compute_parsed_hints')
    status = fields.Selection([
        ('normal', 'Normal'),
        ('warning', 'Warning'),
        ('critical', 'Critical')
    ], string='Status', compute='_compute_status', store=True)

    @api.depends('ai_severity', 'ai_score', 'anomaly_detected')
    def _compute_status(self):
        for rec in self:
            # Priority 1: Use AI severity if we have it
            if rec.ai_severity:
                rec.status = rec.ai_severity
            # Priority 2: Fallback to score thresholds (0-100 scale)
            elif rec.ai_score >= 80:
                rec.status = 'critical'
            elif rec.ai_score >= 50 or rec.anomaly_detected:
                rec.status = 'warning'
            else:
                rec.status = 'normal'
    
    def _compute_parsed_hints(self):
        for rec in self:
            hints = rec.clinical_hints or ""
            if not hints or "normal range" in hints.lower():
                rec.parsed_clinical_hints = "<div class='text-success'><i class='fa fa-check-circle me-2'></i>All vitals within normal range.</div>"
                continue
            
            html = "<div class='sl-clinical-narrative'>"
            parts = [p.strip() for p in hints.split('|')]
            for part in parts:
                if part.startswith('SUMMARY:'):
                    headline = part.replace('SUMMARY:', '')
                    html += f"<div class='alert alert-info border-0 shadow-sm mb-3 py-2' style='border-radius:8px; font-size:0.9em;'><i class='fa fa-info-circle me-2'></i>{headline}</div>"
                
                elif part.startswith('SYSTEM:'):
                    system_name = part.replace('SYSTEM:', '')
                    icon = "fa-lungs" if "Respiratory" in system_name else "fa-heartbeat" if "Cardiovascular" in system_name else "fa-microscope" if "Metabolic" in system_name else "fa-chart-line"
                    html += f"<h6 class='text-uppercase fw-bold text-muted small mt-2 mb-1' style='font-size: 0.75em;'><i class='fa {icon} me-2'></i>{system_name}</h6>"
                
                elif part.startswith('TREND:'):
                    trend_text = part.replace('TREND:', '')
                    icon = "fa-arrow-trend-up" if "increase" in trend_text.lower() else "fa-arrow-trend-down" if "decrease" in trend_text.lower() or "drop" in trend_text.lower() else "fa-chart-line"
                    html += f"<div class='d-flex align-items-center mb-1 text-primary' style='font-size: 0.85em;'><i class='fa {icon} me-2'></i><span>{trend_text}</span></div>"
                
                elif ':' in part:
                    label, val = part.split(':', 1)
                    icon = "fa-warning text-warning"
                    if "CRITICAL" in val.upper(): icon = "fa-exclamation-triangle text-danger"
                    html += f"<div class='d-flex align-items-start mb-1' style='font-size: 0.85em;'><i class='fa {icon} mt-1 me-2' style='width:15px;'></i><b>{label}</b>: {val}</div>"
                else:
                    html += f"<div class='mb-1' style='font-size: 0.85em;'>{part}</div>"
            
            html += "</div>"
            rec.parsed_clinical_hints = html
    
    @api.depends('type')
    def _compute_unit(self):
        units = {
            'blood_pressure': 'mmHg',
            'heart_rate': 'bpm',
            'glucose': 'mg/dL',
            'temperature': '°C',
            'oxygen': '%',
            'respiratory_rate': '/min'
        }
        for rec in self:
            rec.unit = units.get(rec.type, '')

    @api.model_create_multi
    def create(self, vals_list):
        records = super().create(vals_list)
        for rec in records:
            rec._call_ai_service()
        return records

    def write(self, vals):
        res = super().write(vals)
        for rec in self:
            rec._call_ai_service()
        return res

    @api.constrains('patient_id', 'heart_rate', 'bp_systolic', 'bp_diastolic', 'spo2', 'temperature', 'glucose', 'respiratory_rate')
    def _check_first_record_completeness(self):
        for record in self:
            # Only check if this is a "Full Profile" entry or we want broad enforcement
            # The user specifically said: "when i put the first data for a patient it should be all obligatoire"
            
            # Count existing records for this patient
            other_records_count = self.env['health.vital.record'].search_count([
                ('patient_id', '=', record.patient_id.id),
                ('id', '!=', record.id)
            ])
            
            if other_records_count == 0:
                # This is the first record, all core vitals must be > 0
                missing = []
                if not record.heart_rate: missing.append("Heart Rate")
                if not record.bp_systolic: missing.append("Systolic BP")
                if not record.bp_diastolic: missing.append("Diastolic BP")
                if not record.spo2: missing.append("SpO2")
                if not record.temperature: missing.append("Temperature")
                if not record.glucose: missing.append("Glucose")
                if not record.respiratory_rate: missing.append("Respiratory Rate")
                
                if missing:
                    raise ValidationError(
                        _("This is the first record for this patient. "
                          "Please provide a complete baseline by filling: %s") % ", ".join(missing)
                    )

    def _call_ai_service(self):
        if self.env.context.get('no_ai'):
            return
        patient = self.patient_id
        # Optimize: Fetch ALL latest vitals in ONE query
        latest_recs = self.env['health.vital.record'].search([
            ('patient_id', '=', patient.id),
            ('id', '!=', self.id)
        ], order='recorded_at desc')
        
        # Check if this is the first record for this patient
        is_first = not bool(latest_recs)
        
        # Build a robust state history (last 5 states)
        v_fields = ['bp_systolic', 'bp_diastolic', 'heart_rate', 'glucose', 'temperature', 'spo2', 'respiratory_rate']
        history = []
        
        # We want to build 5 snapshots. 
        # For each of the last 5 records, what was the FULL patient state?
        for i in range(min(5, len(latest_recs))):
            snapshot = {}
            # Look at this record and all records older than it
            for r in latest_recs[i:]:
                if len(snapshot) == len(v_fields): break
                for f in v_fields:
                    if f not in snapshot:
                        val = getattr(r, f)
                        # Fallback to generic value fields
                        if not val:
                            if f == 'bp_systolic' and r.type == 'blood_pressure': val = r.value
                            elif f == 'bp_diastolic' and r.type == 'blood_pressure': val = r.value2
                            elif f == 'heart_rate' and r.type == 'heart_rate': val = r.value
                            elif f == 'glucose' and r.type == 'glucose': val = r.value
                            elif f == 'temperature' and r.type == 'temperature': val = r.value
                            elif f == 'spo2' and r.type == 'oxygen': val = r.value
                            elif f == 'respiratory_rate' and r.type == 'respiratory_rate': val = r.value
                        
                        if val: snapshot[f] = val
            
            # Fill remaining with 0.0
            for f in v_fields:
                if f not in snapshot: snapshot[f] = 0.0
            history.append(snapshot)

        # Baseline for the CURRENT reading (snapshot of everything BEFORE current)
        baseline = history[0] if history else {f: 0.0 for f in v_fields}

        payload = {
            'patient_code': str(patient.id),
            'bp_systolic': self.bp_systolic or baseline.get('bp_systolic', 0.0),
            'bp_diastolic': self.bp_diastolic or baseline.get('bp_diastolic', 0.0),
            'heart_rate': self.heart_rate or baseline.get('heart_rate', 0.0),
            'glucose': self.glucose or baseline.get('glucose', 0.0),
            'temperature': self.temperature or baseline.get('temperature', 0.0),
            'spo2': self.spo2 or baseline.get('spo2', 0.0),
            'respiratory_rate': self.respiratory_rate or baseline.get('respiratory_rate', 0.0),
            'history': history,
            'is_initial': is_first
        }

        try:
            resp = requests.post(f'{AI_URL}/analyze', json=payload, timeout=8)
            resp.raise_for_status()
            result = resp.json()
            score = result.get('anomaly_score', 0.0)
            is_anomaly = result.get('is_anomaly', False)
            # Align severity with Odoo's Choice fields
            # AI returns: 'normal', 'warning', 'critical'
            ai_sev = result.get('severity', 'normal')
            record_severity = ai_sev if ai_sev in ['normal', 'warning', 'critical'] else 'normal'
            
            self.sudo().with_context(no_ai=True).write({
                'ai_score': score,
                'ai_severity': record_severity,
                'anomaly_detected': is_anomaly,
                'clinical_hints': result.get('message', '')
            })
            
            patient.sudo().write({
                'last_score': score
            })

            if is_anomaly:
                raw_msg = result.get('message', 'Anomaly detected')
                # Clean up the message to look "normal" by removing [WARNING], etc.
                clean_msg = raw_msg.replace('[WARNING]', '').replace('[CRITICAL]', '').replace('[INFO]', '').strip()
                
                # Severity mapping for the Alert record
                alert_sev_map = {
                    'normal': 'low',
                    'warning': 'high',
                    'critical': 'critical'
                }
                alert_severity = alert_sev_map.get(record_severity, 'low')
                if is_anomaly and alert_severity == 'low':
                    alert_severity = 'medium'

                alert = self.env['health.alert'].sudo().create({
                    'patient_id': patient.id,
                    'vital_record_id': self.id,
                    'severity': alert_severity,
                    'message': clean_msg,
                    'ai_confidence': score, 
                    'state': 'new'
                })
                patient.sudo().write({'last_alert_id': alert.id})
            elif "STABILIZING" in result.get('message', ''):
                # Auto-resolve active alerts if the patient is returning to normal
                active_alerts = self.env['health.alert'].sudo().search([
                    ('patient_id', '=', patient.id),
                    ('state', 'in', ['new', 'acknowledged'])
                ])
                if active_alerts:
                    active_alerts.sudo().write({
                        'state': 'resolved',
                        'resolution_notes': _("System: Patient vitals returned to normal range (Verified by AI in Vital Record #%s)") % self.id
                    })

        except Exception as e:
            _logger.error(f'AI service error: {e}')

    @api.model
    def cron_reanalyze_recent(self):
        cutoff = fields.Datetime.now() - fields.Datetime.subtract(fields.Datetime.now(), hours=2)
        # Using timedelta is usually fine but let's just do search
        from datetime import timedelta
        cutoff = fields.Datetime.now() - timedelta(hours=2)
        recent = self.search([
            ('recorded_at', '>=', cutoff),
        ])
        for rec in recent:
            if not rec.anomaly_detected:
                rec._call_ai_service()
        _logger.info(f'Cron: reanalyzed {len(recent)} recent vital records')
