import os, json, logging, requests
from odoo import models, fields, api

_logger = logging.getLogger(__name__)
AI_URL = os.environ.get('AI_SERVICE_URL', 'http://ai_service:8000')

class HealthVitalRecord(models.Model):
    _name = 'health.vital.record'
    _description = 'Patient Vital Record'
    _order = 'recorded_at desc'

    def action_manual_save_close(self):
        """Dummy method just to give users a 'Save & Close' button that closes the popup wizard"""
        return {'type': 'ir.actions.act_window_close'}

    patient_id = fields.Many2one('health.patient', 'Patient', required=True, ondelete='cascade', index=True)
    type = fields.Selection([
        ('blood_pressure', 'Blood Pressure'),
        ('heart_rate', 'Heart Rate'),
        ('glucose', 'Glucose'),
        ('temperature', 'Temperature'),
        ('oxygen', 'Oxygen (SpO2)'),
        ('respiratory_rate', 'Respiratory Rate')
    ], string='Vital Type')
    
    value = fields.Float('Value/Systolic')
    value2 = fields.Float('Diastolic (for BP)')
    unit = fields.Char('Unit', compute='_compute_unit', store=True)

    recorded_at = fields.Datetime('Recorded At', default=fields.Datetime.now, required=True, index=True)
    
    ai_score = fields.Float('AI Score', readonly=True, help="Probability score from 0.0 to 1.0 generated by the Isolation Forest.")
    anomaly_detected = fields.Boolean('Anomaly Detected', readonly=True, help="True if ML or Rule thresholds were violated.")
    
    # NEW FIELDS DEMANDED BY THE VIEW
    bp_systolic = fields.Float('BP Systolic')
    bp_diastolic = fields.Float('BP Diastolic')
    heart_rate = fields.Float('Heart Rate')
    spo2 = fields.Float('SpO2')
    temperature = fields.Float('Temperature')
    glucose = fields.Float('Glucose')
    respiratory_rate = fields.Float('Respiratory Rate')
    clinical_hints = fields.Text('Clinical Hints')
    parsed_clinical_hints = fields.Html('AI Clinical Analysis', compute='_compute_parsed_hints')
    status = fields.Selection([
        ('normal', 'Normal'),
        ('warning', 'Warning'),
        ('critical', 'Critical')
    ], string='Status', compute='_compute_status', store=True)

    @api.depends('anomaly_detected', 'ai_score')
    def _compute_status(self):
        for rec in self:
            if rec.ai_score >= 0.8:
                rec.status = 'critical'
            elif rec.anomaly_detected:
                rec.status = 'warning'
            else:
                rec.status = 'normal'
    
    def _compute_parsed_hints(self):
        for rec in self:
            hints = rec.clinical_hints or ""
            if not hints or "normal range" in hints.lower():
                rec.parsed_clinical_hints = "<div class='text-success'><i class='fa fa-check-circle me-2'></i>All vitals within normal range.</div>"
                continue
            
            # Professional medical formatting
            html = "<ul class='list-unstyled mb-0'>"
            parts = [p.strip() for p in hints.split('|')]
            for part in parts:
                icon = "fa-warning text-warning"
                if "CRITICAL" in part.upper(): icon = "fa-exclamation-triangle text-danger"
                
                # Highlight the vital name
                if "=" in part:
                    vital_name = part.split('=')[0].replace('_', ' ').title()
                    the_rest = part.split('=', 1)[1]
                    part_html = f"<b>{vital_name}</b>: {the_rest}"
                else:
                    part_html = part
                
                html += f"<li class='mb-2 d-flex align-items-start'><i class='fa {icon} mt-1 me-2' style='width: 20px;'></i><span>{part_html}</span></li>"
            html += "</ul>"
            rec.parsed_clinical_hints = html
    
    @api.depends('type')
    def _compute_unit(self):
        units = {
            'blood_pressure': 'mmHg',
            'heart_rate': 'bpm',
            'glucose': 'mg/dL',
            'temperature': '°C',
            'oxygen': '%',
            'respiratory_rate': '/min'
        }
        for rec in self:
            rec.unit = units.get(rec.type, '')

    @api.model_create_multi
    def create(self, vals_list):
        records = super().create(vals_list)
        for rec in records:
            rec._call_ai_service()
        return records

    def write(self, vals):
        res = super().write(vals)
        for rec in self:
            rec._call_ai_service()
        return res

    def _call_ai_service(self):
        if self.env.context.get('no_ai'):
            return
        patient = self.patient_id
        latest = {}
        for t in ['blood_pressure', 'heart_rate', 'glucose', 'temperature', 'oxygen', 'respiratory_rate']:
            rec = self.env['health.vital.record'].search([('patient_id', '=', patient.id), ('type', '=', t)], limit=1, order='recorded_at desc')
            latest[t] = rec

        payload = {
            'patient_code': str(patient.id),
            'bp_systolic': self.bp_systolic or (latest['blood_pressure'].value if latest['blood_pressure'] else 0.0),
            'bp_diastolic': self.bp_diastolic or (latest['blood_pressure'].value2 if latest['blood_pressure'] else 0.0),
            'heart_rate': self.heart_rate or (latest['heart_rate'].value if latest['heart_rate'] else 0.0),
            'glucose': self.glucose or (latest['glucose'].value if latest['glucose'] else 0.0),
            'temperature': self.temperature or (latest['temperature'].value if latest['temperature'] else 0.0),
            'spo2': self.spo2 or (latest['oxygen'].value if latest['oxygen'] else 0.0),
            'respiratory_rate': self.respiratory_rate or (latest['respiratory_rate'].value if latest['respiratory_rate'] else 0.0),
        }

        try:
            resp = requests.post(f'{AI_URL}/analyze', json=payload, timeout=8)
            resp.raise_for_status()
            result = resp.json()
            score = result.get('anomaly_score', 0.0)
            is_anomaly = result.get('is_anomaly', False)
            severity = result.get('severity', 'low')
            
            # Align severities with Odoo selection options
            if severity == 'critical':
                odoo_severity = 'critical'
            elif severity == 'warning':
                odoo_severity = 'high'
            elif is_anomaly:
                odoo_severity = 'medium'
            else:
                odoo_severity = 'low'
            
            self.with_context(no_ai=True).write({
                'ai_score': score,
                'anomaly_detected': is_anomaly,
                'clinical_hints': result.get('message', '')
            })
            
            patient.write({
                'last_score': score,
                'risk_level': odoo_severity
            })

            if is_anomaly:
                raw_msg = result.get('message', 'Anomaly detected')
                # Clean up the message to look "normal" by removing [WARNING], etc.
                clean_msg = raw_msg.replace('[WARNING]', '').replace('[CRITICAL]', '').replace('[INFO]', '').strip()
                
                alert = self.env['health.alert'].create({
                    'patient_id': patient.id,
                    'vital_record_id': self.id,
                    'severity': odoo_severity,
                    'message': clean_msg,
                    'ai_confidence': score, 
                    'state': 'new'
                })
                patient.write({'last_alert_id': alert.id})

        except Exception as e:
            _logger.error(f'AI service error: {e}')

    @api.model
    def cron_reanalyze_recent(self):
        cutoff = fields.Datetime.now() - fields.Datetime.subtract(fields.Datetime.now(), hours=2)
        # Using timedelta is usually fine but let's just do search
        from datetime import timedelta
        cutoff = fields.Datetime.now() - timedelta(hours=2)
        recent = self.search([
            ('recorded_at', '>=', cutoff),
        ])
        for rec in recent:
            if not rec.anomaly_detected:
                rec._call_ai_service()
        _logger.info(f'Cron: reanalyzed {len(recent)} recent vital records')
