[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = db
db_port = 5432
db_name = smartlab_db
admin_passwd = amine
http_port = 8069
http_interface = 0.0.0.0
log_level = info
workers = 2
max_cron_threads = 1
proxy_mode = True
list_db = False
