{
    'name': 'Health Monitoring & AI Alerts',
    'version': '17.0.1.0.4',
    'category': 'Healthcare',
    'summary': 'Real-time patient vitals monitoring with ML anomaly detection',
    'author': 'SmartLab 2026',
    'license': 'LGPL-3',
    'depends': ['base', 'mail'],
    'data': [
        'security/security_groups.xml',
        'security/security_rules.xml',
        'security/mail_security_rules.xml',
        'security/ir.model.access.csv',
        'data/performance_indexes.xml',
        'data/sequence.xml',
        'reports/patient_history_report.xml',
        'reports/alert_statistics_report.xml',
        'views/health_vital_record_views.xml',
        'views/health_alert_views.xml',
        'views/health_patient_views.xml',
        'views/health_ward_views.xml',
        'views/health_handoff_views.xml',
        'wizard/alert_resolve_wizard_views.xml',
        'wizard/vital_confirm_wizard_views.xml',
        'wizard/patient_admit_wizard_views.xml',
        'views/dashboard_views.xml',
        'views/menus.xml',
        'views/res_users_views.xml',
        'data/cron.xml',
    ],
    'demo': [
        'data/demo_hospital_data.xml',
        'data/demo_action.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'health_monitoring/static/src/scss/smartlab_theme.scss',
            'health_monitoring/static/src/scss/smartlab_dashboards.scss',
            'health_monitoring/static/src/xml/nurse_dashboard.xml',
            'health_monitoring/static/src/xml/doctor_dashboard.xml',
            'health_monitoring/static/src/xml/admin_dashboard.xml',
            'health_monitoring/static/src/xml/dashboard_router.xml',
            'health_monitoring/static/src/js/nurse_dashboard.js',
            'health_monitoring/static/src/js/doctor_dashboard.js',
            'health_monitoring/static/src/js/admin_dashboard.js',
            'health_monitoring/static/src/js/dashboard_router.js',
            'health_monitoring/static/src/xml/analytics_dashboard.xml',
            'health_monitoring/static/src/js/analytics_dashboard.js',
            'health_monitoring/static/src/js/vital_safety_check.js',
            'health_monitoring/static/src/xml/vital_confirm_dialog.xml',
            'health_monitoring/static/src/js/vital_confirm_dialog.js',
        ],
    },
    'installable': True,
    'application': True,
}
