{
    'name': 'Health Monitoring & AI Alerts',
    'version': '17.0.1.0.4',
    'category': 'Healthcare',
    'summary': 'Real-time patient vitals monitoring with ML anomaly detection',
    'author': 'SmartLab 2026',
    'license': 'LGPL-3',
    'depends': ['base', 'mail'],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'views/health_vital_record_views.xml',
        'views/health_alert_views.xml',
        'views/health_patient_views.xml',
        'views/dashboard_views.xml',
        'views/menus.xml',
        'views/res_users_views.xml',
        'data/cron.xml',
        'data/demo_action.xml',
        'reports/patient_history_report.xml',
        'reports/alert_statistics_report.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap',
            'health_monitoring/static/src/scss/smartlab_theme.scss',
        ],
    },
    'installable': True,
    'application': True,
}